export const Contents = {
    filmTitleAdopted: 'Бойцовский клуб (1999)',
    filmTitleOriginal: 'Fight club',
    filmJenres: ['Триллер', 'Драма', 'Криминал'],
    filmCountries: ['США', 'Германия'],
    filmDirector: 'Дэвид Финчер',
    filmTagline: '"Интриги. Хаос. Мыло"',
    filmDescription:
        'Сотрудник страховой компании страдает хронической бессонницей и отчаянно пытается вырваться из мучительно скучной жизни. Однажды в очередной командировке он встречает некоего Тайлера Дёрдена — харизматического торговца мылом с извращенной философией. Тайлер уверен, что самосовершенствование — удел слабых, а единственное, ради чего стоит жить, — саморазрушение. Проходит немного времени, и вот уже новые друзья лупят друг друга почем зря на стоянке перед баром, и очищающий мордобой доставляет им высшее блаженство. Приобщая других мужчин к простым радостям физической жестокости, они основывают тайный Бойцовский клуб, который начинает пользоваться невероятной популярностью.',
    filmActors: [
        { name: 'Эдвард Нортон', url: 'https://www.kinopoisk.ru/name/25774/' },
        { name: 'Брэд Питт', url: 'https://www.kinopoisk.ru/name/25584/' },
        { name: 'Хелена Бонем Картер', url: 'https://www.kinopoisk.ru/name/25775/' },
        { name: 'Мит Лоаф', url: 'https://www.kinopoisk.ru/name/14127/' },
        { name: 'Зэк Гренье', url: 'https://www.kinopoisk.ru/name/25776/' },
        { name: 'Холт Маккэллани', url: 'https://www.kinopoisk.ru/name/8151/' },
    ],
    teamMembers: [
        { id: 0, name: 'Valerii Dycahsnkyi', position: 'Programmer' },
        { id: 1, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 2, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 3, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 4, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 5, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 6, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 7, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 8, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 9, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 10, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 11, name: 'John Doe', position: 'Trailer Editing', image: '' },
        { id: 12, name: 'John Doe', position: 'Trailer Editing', image: '' },
    ],
    officialSocialMedias: [
        { id: 0, url: '', title: 'Facebook', imageSrc: 'images/facebook-icon.png' },
        { id: 1, url: '', title: 'Vk', imageSrc: 'images/vkpng.png' },
        { id: 2, url: '', title: 'Twitter', imageSrc: 'images/twitter.png' },
    ],
};
