export const Contents = {
    filmTitleAdopted: 'Бойцовский клуб (1999)',
    filmTitleOriginal: 'Fight club',
    filmJenres: ['Триллер', 'Драма', 'Криминал'],
    filmCountries: ['США', 'Германия'],
    filmDirector: 'Дэвид Финчер',
    filmTagline: '"Интриги. Хаос. Мыло"',
    filmDescription:
        'Сотрудник страховой компании страдает хронической бессонницей и отчаянно пытается вырваться из мучительно скучной жизни. Однажды в очередной командировке он встречает некоего Тайлера Дёрдена — харизматического торговца мылом с извращенной философией. Тайлер уверен, что самосовершенствование — удел слабых, а единственное, ради чего стоит жить, — саморазрушение. Проходит немного времени, и вот уже новые друзья лупят друг друга почем зря на стоянке перед баром, и очищающий мордобой доставляет им высшее блаженство. Приобщая других мужчин к простым радостям физической жестокости, они основывают тайный Бойцовский клуб, который начинает пользоваться невероятной популярностью.',
    filmActors: [
        { name: 'Эдвард Нортон', url: 'https://www.kinopoisk.ru/name/25774/' },
        { name: 'Брэд Питт', url: 'https://www.kinopoisk.ru/name/25584/' },
        { name: 'Хелена Бонем Картер', url: 'https://www.kinopoisk.ru/name/25775/' },
        { name: 'Мит Лоаф', url: 'https://www.kinopoisk.ru/name/14127/' },
        { name: 'Зэк Гренье', url: 'https://www.kinopoisk.ru/name/25776/' },
        { name: 'Холт Маккэллани', url: 'https://www.kinopoisk.ru/name/8151/' },
    ],
    teamMembers: [
        { id: 0, name: 'Валерий Дичанский', position: 'Programmer', image: 'images/team/8.jpg' },
        { id: 1, name: 'Александр Прохоров', position: 'Speaker', image: 'images/team/1.jpg' },
        { id: 2, name: 'Иван Скрындица', position: 'Trailer Editing', image: 'images/team/2.jpg' },
        { id: 3, name: 'Софья Калиниченко', position: 'Scrum master', image: 'images/team/3.jpg' },
        { id: 4, name: 'Попов Кирилл', position: 'Scrum master', image: 'images/team/4.jpg' },
        { id: 5, name: 'Ольга Голиш', position: 'Design/Marketing', image: 'images/team/5.jpg' },
        { id: 6, name: 'Михаил Ципилев', position: 'Art/Design', image: '' },
        { id: 7, name: 'Элина Ломака', position: 'Copyrighting', image: 'images/team/10.jpg' },
        { id: 8, name: 'Карпенко Катерина', position: 'Information reserch', image: '' },
        { id: 9, name: 'Сергей Вербивский', position: 'Information reserch', image: 'images/team/6.jpg' },
        { id: 10, name: 'Дмитрий Бабиев', position: 'Presentation', image: 'images/team/7.jpg' },
        { id: 11, name: 'Максим Лафазан', position: 'Presentation', image: '' },
        { id: 12, name: 'Алексей Моргунов', position: 'Copyrighting', image: 'images/team/9.jpg' },
        { id: 13, name: 'Анастасия Хорошева', position: 'Information reserch', image: '' },
    ],
    officialSocialMedias: [
        { id: 0, url: '', title: 'Facebook', imageSrc: 'images/facebook-icon.png' },
        { id: 1, url: '', title: 'Vk', imageSrc: 'images/vkpng.png' },
        { id: 2, url: '', title: 'Twitter', imageSrc: 'images/twitter.png' },
    ],
    faq: [
        {
            id: 0,
            question: 'Первое правило Бойцовского клуба знают все. А какое последнее правило ?',
            answer: 'Тот, кто впервые пришел в клуб — примет бой.',
        },
        {
            id: 1,
            question: 'Как зовут главного героя?',
            answer: 'Неизвестно. Обычно героя Эдварда Нортона называют Рассказчиком, ведь ни в фильме, ни в книге не упоминается его настоящее имя. Тайлер — это его альтер-эго. В группах поддержки он представляется разными вымышленными именами: Руперт, Тревис, Корнелиус. Иногда Рассказчик произносит фразы вроде «я - ухмыляющаяся месть Джека», но это лишь отсылки к статьям журнала «Ридерз Дайджест», которые он читает.',
        },
        {
            id: 2,
            question: 'Рецепт напалма от Тайлера?',
            answer: 'Бензин и апельсиновый сок. Бомба из этих ингредиентов не получится. По понятным причинам создатели фильма не стали делиться рабочим способом изготовления взрывчатки.',
        },
        {
            id: 3,
            question: 'Чем Тайлер НЕ занимался?',
            answer: 'Не продавал краденые джинсы. Ну, конечно! Этим занималась Марла Сингер — воровала чужие джинсы из прачечной и сдавала их в комиссионку.',
        },
        {
            id: 4,
            question: 'Какое животное покровительствует Рассказчику?',
            answer: 'Пингвин',
        },
        {
            id: 5,
            question: 'В каком месте главный герой познакомился с Тайлером?',
            answer: 'В самолёте.',
        },
        {
            id: 6,
            question: 'Чем занимался главный герой, сидя на унитазе?',
            answer: 'Заказывал чехлы для кровати Эрики Пеккари.',
        },
        {
            id: 7,
            question: 'Что в первую очередь делал Тайлер в старом доме, когда начинался дождь?',
            answer: 'Отключал электричество.',
        },
    ],
};
